### ISSUE TITLE
Session problem with uwsgi multi-process

### ISSUE THREAD

**Issue by ddurieux** [Alignak-monitoring-contrib/alignak-webui#2]
If we run uwsgi with multiprocess (_-p 4_ for example) and we connect to webui it return to login page because sessions seems not shared between processes

**Comment by ddurieux** [comment]
In Beaker documentation, the _session.type_ defined to _memory_ will not be shared between different processes, to need to set to _file_ but with that I have error when login

**Comment by mohierf** [comment]
Yes, I made this test ... the session type cannot be set to _file_ because Beaker need to pickle the objects and some stored objects are not pickleable, and the Beaker `json` parameter is buggy !

Perharps we may test another session storage ... perharps `ext:memcached` will be the best choice ?

_Anyway, the application runs perfectly with `uwsgi` single process on my Debian configuration ..._

**Comment by ddurieux** [comment]
With memcached it could be great because sessions can be shared between different servers (in case create clster of webui).

(Yes with single process it works but you limit the power of the wsgi :p)

**Comment by mohierf** [comment]
What about storing session parameters in the Alignak backend ... to be discussed ! It may be possible to add an extension to the Beaker object to store json session parameters in the Alignak backend mongo DB ...

**Comment by mohierf** [comment]
Beaker support storing session parameters in a database complying with SQL Alchemy ...

**Comment by ddurieux** [comment]
Yes but require install sqlalchemy + a database only for that, so seems require too work for admin install it and maintain.
