### ISSUE TITLE
Manage plugin or theme ?

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-webui#83]
**Enhancement Ideas**

If I remember well, there will theme capability for webui.

But for future versions, does Webui support plugins like Gravatar support, LDAP auth, ... Or maybe include this inside directly ?

**Comment by mohierf** [comment]
To be discussed...

**1/** For user authentication, the WebUI uses the Alignak backend. It may be difficult to use something like Gravatar or LDAP instead of this

**2/** For theming, we are now using Bootstrap Material design and the theming is fully supported through CSS. Perharps we could choose which CSS file is loaded in the WebUI configuration file

**Comment by algorys** [comment]
**1.1/** I think Alignak Suite must have LDAP authentication. Most software offers this fonctionnality. Maybe backend can manage that and discuss with Webui to send Token auth ? I'm not an expert for that...

**1.2/** Gravatar support is not necessarily essential. It's just funny :laughing: 

**2/** Yes I think it'll be good in configuration file or reachable from WebUI directly.

**Comment by mohierf** [comment]
For 1.1, open an issue for the Alignak backend.

For 1.2 and 1.3, open an issue in this project
